// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.Data;

#nullable disable

namespace UserService.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.model.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("e732f56c-c78c-4983-94c5-48701fc0c5c2"),
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 8, 1, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "jdoe@gmail.com",
                            IsAdmin = false,
                            Password = "password123",
                            UpdatedAt = new DateTimeOffset(new DateTime(2023, 8, 15, 11, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)),
                            UserName = "jdoe"
                        },
                        new
                        {
                            UserId = new Guid("8cd17c38-55aa-4843-9b55-654444de4cac"),
                            CreatedAt = new DateTimeOffset(new DateTime(2022, 12, 5, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            Email = "asmith@yahoo.com",
                            IsAdmin = true,
                            Password = "securePass!23",
                            UpdatedAt = new DateTimeOffset(new DateTime(2023, 2, 12, 15, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            UserName = "asmith"
                        },
                        new
                        {
                            UserId = new Guid("c62169c1-0285-49ed-87ee-1ebd1ce52f4d"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 6, 21, 8, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "mwhite@gmail.com",
                            IsAdmin = false,
                            Password = "White@45",
                            UpdatedAt = new DateTimeOffset(new DateTime(2023, 1, 10, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -6, 0, 0, 0)),
                            UserName = "mwhite"
                        },
                        new
                        {
                            UserId = new Guid("5d80b63c-6f3a-473b-bc2d-7ad957a9753c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2020, 4, 30, 17, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)),
                            Email = "ljones@hotmail.com",
                            IsAdmin = true,
                            Password = "Jones$789",
                            UpdatedAt = new DateTimeOffset(new DateTime(2023, 10, 9, 19, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -5, 0, 0, 0)),
                            UserName = "ljones"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
